### PR TITLE
Update Swift version for SPM & fix tests

### PR DESCRIPTION
**Pull request by UInt2048**
Thanks to @SportlabsTechnology and David Sansome, I was able to re-introduce proper Swift Package Manager support and fix the unit tests.

### CODE REVIEW

**Comment by turtlemaster19** [comment]
So, it's not exactly passing, but maybe this could help for debugging? I'm not at my home computer right now, so I don't have Xcode available. 😉

**Comment by turtlemaster19** [comment]
It builds in the Linux test and all tests function locally on my Mac. I'm not sure what's going on with the TravisCI test target.

**Comment by turtlemaster19** [comment]
@vadymmarkov, tests are passing now.

**Comment by UInt2048** [comment]
@vadymmarkov, tests are passing now.
Once you merge this, can you make a release so that I can use SwiftPM in another repository to depend on this one?
P.S. If you want, I can update the Swift version to the current 5/5.1 without changing the code, just some config files and stuff. 😉 Just let me know if I should send another PR doing that after this is merged.

**Comment by vadymmarkov** [comment]
Thanks @turtlemaster19. Swift 5.1 migration would be great 😉

**Comment by UInt2048** [comment]
@vadymmarkov By the way, there were a few breaking changes when the return type of some functions in `Regex.swift` changed from `String` to `Substring`. Although it's beneficial, you may want to [edit the releases](https://help.github.com/en/github/administering-a-repository/editing-and-deleting-releases) to 1.0.0 and 1.0.1 to signal that there were breaking changes.

**Pull request merged**
