### PR TITLE
Update Swift version in Package.swift

### PR DESCRIPTION
**Pull request by UInt2048**
These changes are required to work with the latest Xcode version, and updates the Swift version to 4.0. In addition, the update to 4.0 in Package.swift is also required in the latest version.

@vadymmarkov, if you would like me to change anything, please let me know.

**EDIT:** Sorry about all the force-pushing.

### CODE REVIEW

**Review by vadymmarkov — APPROVED** [review]
Thanks 👍

**Review by vadymmarkov — COMMENTED** [review]
Any idea why tests are failing?

**Comment by turtlemaster19** [comment]
It may have to do with a header named `block.h` in the replace test. I don't have much more to tell you, sorry.

**Comment by turtlemaster19** [comment]
Does the framework import `CoreFoundation` by any chance?

**Comment by UInt2048** [comment]
Actually, I think I know. Let me try a new PR, so I can get rid of all the force pushing and closing/reopening. I will try again at #14

**Pull request closed without merging**
